# Default values for rancher-importer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

manifestUrl: ""
clientCertificate: ""
clientKey: ""
clusterCACertificate: ""
